name: build
on:
  push:
    # branches: [ $default-branch, ar-test ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20, 22, 24 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test

      - name: test coverage
        if: ${{ matrix.node == '24' }}
        run: npm run coverage
      - name: upload coverage
        if: ${{ matrix.node == '24' }}
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
